version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  webapp:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
      - redis